version: "3.2"
services:
  influxdb:
    image: influxdb
    user: "root"
    ports:
      - "8086:8086"
    network_mode: "host"
    restart: "always"
    volumes:
      - type: volume
        source: ./influx/data
        target: /var/lib/influxdb
  telegraf:
    container_name: telegraf
    image: telegraf:1.9.4-alpine
    network_mode: "host"
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
